<a href="https://colab.research.google.com/github/JAMUNAASHREE18/jamunaa-codebooster1-2026/blob/main/Day7/Day7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install chromadb sentence-transformers -q
print('installation completes!')

installation completes!


In [ ]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
import chromadb

print("All libraries imported successfully!")
print(f'ChromaDB version: {chromadb.__version__}')

All libraries imported successfully!
ChromaDB version: 1.5.9


In [ ]:
documents=[
    "ETL is used to clean and transform data",  #doc_0
    "A vechile is a mode of transportation",  #doc_1
    "Cars and trucks are popular automobile",  #doc_2
    "SQL is used to query database",    #doc_3
    "Machine learning trains models on data"   #doc_4
]

query_keyword="vechile"

print("="*60)
print(f"KEYWORD SEARCH for:'{query_keyword}'")
print("="*60)

for i,doc in enumerate(documents):
  if query_keyword.lower() in doc.lower():
    print(f" FOUND  [doc_{i}]:{doc}")
  else:
    print(f" MISSED [doc_{i}]:{doc}")
print()
print("PROBLEM:doc_2 talks about 'Cars and trucks'-which ARE vechicles!")
print("But keywords search MISSED it because it searcher for the exact word'vechile'.")

KEYWORD SEARCH for:'vechile'
 MISSED [doc_0]:ETL is used to clean and transform data
 FOUND  [doc_1]:A vechile is a mode of transportation
 MISSED [doc_2]:Cars and trucks are popular automobile
 MISSED [doc_3]:SQL is used to query database
 MISSED [doc_4]:Machine learning trains models on data

PROBLEM:doc_2 talks about 'Cars and trucks'-which ARE vechicles!
But keywords search MISSED it because it searcher for the exact word'vechile'.


In [ ]:
print("Loading embedding model...(may take 1-2 mins on 1st run)")
model=SentenceTransformer('all-MiniLM-L6-v2')
print("Model loaded successfully!")
print(f"Model produces vectory of size:{model.get_sentence_embedding_dimension()} dimensions")

Loading embedding model...(may take 1-2 mins on 1st run)


Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


Model loaded successfully!
Model produces vectory of size:384 dimensions


/tmp/ipykernel_1959/863537265.py:4: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  print(f"Model produces vectory of size:{model.get_sentence_embedding_dimension()} dimensions")


In [ ]:
sentence="ETL is used to clean and transform data"

embedding=model.encode(sentence)
print(f"Input sentence:'{sentence}'")
print()
print(f"Embedding type:{type(embedding)}")
print(f"Embedding shape:{embedding.shape}")
print(f"First 10 numbers:{embedding[:10].round(4)}")
print(f"Min valuue:{embedding.min():.4f}")
print(f"Max valuue:{embedding.max():.4f}")

Input sentence:'ETL is used to clean and transform data'

Embedding type:<class 'numpy.ndarray'>
Embedding shape:(384,)
First 10 numbers:[-0.0784  0.0541  0.0224 -0.0389  0.0221 -0.0904  0.0007 -0.0152  0.0733
  0.0362]
Min valuue:-0.1381
Max valuue:0.1815


In [ ]:
sentences = [
    "ETL is used to clean and transfrom data",    #doc_1
    "A vehicle is a mode of transport",            #doc_2
    "cars and trucks are popular transport",      #doc_3
    "SQL is used to query databases",             #doc_4
    "Machine learning trains model on data"       #doc_5

]

embedding = model.encode(sentences)

print(f'input sentence: {sentences}')
print()
print(f'embedding format {type(embedding)}')

print(f'embedding shape {embedding.shape}')

print(f"First 10 numbers:{embedding[:10].round(4)}")
print(f"Min valuue:{embedding.min():.4f}")
print(f"Max valuue:{embedding.max():.4f}")

query_keyword='vehicle'
query_embedding = model.encode([query_keyword])
similarities = np.dot(query_embedding, embedding.T)
similarities = similarities[0]
similarity_threshold = 0.5

print("\nSemantic Search Results:")
for i , doc in enumerate(sentences):
  current_similarity = similarities[i]
  if current_similarity >= similarity_threshold:
    print(f'found  [doc_{i}] (Similarity: {current_similarity:.4f}): {doc}')
  else:
    print(f'missed [doc_{i}] (Similarity: {current_similarity:.4f}): {doc}')

print()

input sentence: ['ETL is used to clean and transfrom data', 'A vehicle is a mode of transport', 'cars and trucks are popular transport', 'SQL is used to query databases', 'Machine learning trains model on data']

embedding format <class 'numpy.ndarray'>
embedding shape (5, 384)
First 10 numbers:[[-0.0595  0.0287  0.0238 ...  0.0128  0.0648 -0.0089]
 [ 0.0117 -0.0087 -0.0039 ...  0.0802  0.0565 -0.0184]
 [ 0.0964 -0.062   0.025  ...  0.0403  0.0741  0.0555]
 [ 0.0298 -0.0137 -0.0951 ...  0.0411  0.0983 -0.0323]
 [-0.056  -0.0846  0.0477 ... -0.0022 -0.015  -0.0374]]
Min valuue:-0.1890
Max valuue:0.1726

Semantic Search Results:
missed [doc_0] (Similarity: 0.0903): ETL is used to clean and transfrom data
found  [doc_1] (Similarity: 0.6972): A vehicle is a mode of transport
found  [doc_2] (Similarity: 0.5354): cars and trucks are popular transport
missed [doc_3] (Similarity: 0.1030): SQL is used to query databases
missed [doc_4] (Similarity: 0.2150): Machine learning trains model on data


In [ ]:
sentence=[
    "ETL is used to clean and transform data",
    "Dta transformation is a key pipeline step",
    "The sky is blue and cloud are white"
]
embeddings = model.encode(sentences)

print(f"Number of sentences:{len(sentences)}")
print(f"Shape of embeddings array:{embeddings.shape}")
print()
print("Each row is onne sentence's embedding:")
for i,sent in enumerate(sentences):
  print(f" Sentence{i}:shape{embeddings[i].shape},first 5 values={embedding[i][:5]}")

Number of sentences:5
Shape of embeddings array:(5, 384)

Each row is onne sentence's embedding:
 Sentence0:shape(384,),first 5 values=[-0.05952802  0.02865169  0.0238291  -0.0285144   0.02187212]
 Sentence1:shape(384,),first 5 values=[ 0.01167519 -0.00869449 -0.00385204  0.05013036  0.00688688]
 Sentence2:shape(384,),first 5 values=[ 0.09636056 -0.06204591  0.02499741  0.05156663  0.04053951]
 Sentence3:shape(384,),first 5 values=[ 0.02984659 -0.01370841 -0.09513693  0.04836753 -0.08524196]
 Sentence4:shape(384,),first 5 values=[-0.05601997 -0.08462865  0.04773796  0.11239294 -0.00252916]


In [ ]:
your_sentence = [
    "I like travel the world",
    "I want to go different country",
    "I want vacation this year"
    "Enjoy the life"
]
key_words = ["vacation"]

your_sentence_embedding = model.encode(your_sentence)
key_words_embedding = model.encode(key_words)

similarity_matrix = np.dot(key_words_embedding, your_sentence_embedding.T)
similarity_threshold = 0.45
print("Keyword Semantic Search Results")
for i, keyword in enumerate(key_words):
    print(f"Keyword: '{keyword}'")
    print("-" * 30)
    for j, sentence in enumerate(your_sentence):
        similarity_score = similarity_matrix[i][j]
        if similarity_score >= similarity_threshold:
            print(f"  FOUND  | Score: {similarity_score:.4f} | '{sentence}'")
        else:
            print(f"  MISSED | Score: {similarity_score:.4f} | '{sentence}'")
    print()

Keyword Semantic Search Results
Keyword: 'vacation'
------------------------------
  FOUND  | Score: 0.5070 | 'I like travel the world'
  MISSED | Score: 0.2757 | 'I want to go different country'
  FOUND  | Score: 0.6695 | 'I want vacation this yearEnjoy the life'



In [ ]:
chroma_client=chromadb.Client()

collection=chroma_client.get_or_create_collection("demo_notes")

print("ChromaDB client created(in-memory model)")
print(f"Collection name:demo_name")
print(f"Documents in collection:{collection.count()}")

ChromaDB client created(in-memory model)
Collection name:demo_name
Documents in collection:0


In [ ]:
sample_docs=[
    "ETL is used to clean and transfrom data",    #doc_1
    "A vehicle is a mode of transport",            #doc_2
    "cars and trucks are popular transport",      #doc_3
    "SQL is used to query databases",             #doc_4
    "Machine learning trains model on data"       #doc_5

]

sample_ids=["doc_1","doc_2","doc_3","doc_4","doc_5"]
#sample_ids=["doc001","doc002","doc003","doc004","doc005"]

sample_metadata=[
    {"subject":"Data Engineering","topic":"ETL"},
    {"subject":"Data Engineering","topic":"SQL"},
    {"subject":"ML","topic":"ML Bacis"},
    {"subject":"Python","topic":"Pandas"},
    {"subject":"ML","topic":"Neural Networks"}
]
collection.add(
    documents=sample_docs,
    ids=sample_ids,
    metadatas=sample_metadata
)

print(f"Documents adder to collection!")
print(f"Total doc now in collection:{collection.count()}")

Documents adder to collection!
Total doc now in collection:5


In [ ]:
quer="How do I clean and prepare data?"

results=collection.query(
    query_texts=[quer],
    n_results=3
)

print("RESULT KEYS AVAILABLE:")
print(list(results.keys()))

RESULT KEYS AVAILABLE:
['ids', 'embeddings', 'documents', 'uris', 'included', 'data', 'metadatas', 'distances']


In [ ]:
print(f"Query:'{quer}'")
print("="*60)
print()
matched_docs=results['documents'][0]
matched_ids=results['ids'][0]
matched_distances=results['distances'][0]
matched_metadata=results['metadatas'][0]

for rank,(doc,doc_id,dist,meta) in enumerate(zip(matched_docs,matched_ids,matched_distances,matched_metadata),start=1):
  print(f"Rank{rank}|ID:{doc_id}|Distance:{dist:.4f}")
  print(f"Subject:{meta['subject']}|Topic:{meta['topic']}")
  print(f"Document:{doc}")
  print()
  print("NOTICE:The result are above ETL & pandas")
  print("Semantic search found them even though the words are different")

Query:'How do I clean and prepare data?'

Rank1|ID:doc_1|Distance:1.1896
Subject:Data Engineering|Topic:ETL
Document:ETL is used to clean and transfrom data

NOTICE:The result are above ETL & pandas
Semantic search found them even though the words are different
Rank2|ID:doc_4|Distance:1.5369
Subject:Python|Topic:Pandas
Document:SQL is used to query databases

NOTICE:The result are above ETL & pandas
Semantic search found them even though the words are different
Rank3|ID:doc_5|Distance:1.6966
Subject:ML|Topic:Neural Networks
Document:Machine learning trains model on data

NOTICE:The result are above ETL & pandas
Semantic search found them even though the words are different


In [ ]:
print(f'Query: "{quer}"')
print()

matched_docs = results['documents'][0]
matched_distances = results['distances'][0]
matched_ids = results['ids'][0]
matched_metadatas = results['metadatas'][0]

for rank, (doc, dist, doc_id, meta) in enumerate(zip(matched_docs, matched_distances, matched_ids, matched_metadatas)):
    print(f'Rank {rank} | ID: {doc_id} | Distance: {dist:.4f}')
    print(f"subject: {meta['subject']}")
    print(f"topic: {meta['topic']}")
    print(f"document: {doc}")
    print()

Query: "How do I clean and prepare data?"

Rank 0 | ID: doc_1 | Distance: 1.1896
subject: Data Engineering
topic: ETL
document: ETL is used to clean and transfrom data

Rank 1 | ID: doc_4 | Distance: 1.5369
subject: Python
topic: Pandas
document: SQL is used to query databases

Rank 2 | ID: doc_5 | Distance: 1.6966
subject: ML
topic: Neural Networks
document: Machine learning trains model on data



In [ ]:
# 1. Run the query with the ML subject filter
filter_results = collection.query(
    query_texts=[quer],
    n_results=3,
    where={"subject": "ML"}
)

print(f"FILTER QUERY: '{quer}'")
print("=" * 60)
print("Filter: Only ML documents\n")
for rank, (doc, dist, meta) in enumerate(zip(
    filter_results['documents'][0],
    filter_results['distances'][0],
    filter_results['metadatas'][0]
), start=1):
    print(f"Rank {rank} | Distance: {dist:.4f} | Subject: {meta['subject']}")
    print(f"  {doc}")
    print()

FILTER QUERY: 'How do I clean and prepare data?'
Filter: Only ML documents

Rank 1 | Distance: 1.6966 | Subject: ML
  Machine learning trains model on data

Rank 2 | Distance: 2.0438 | Subject: ML
  cars and trucks are popular transport



In [ ]:
from huggingface_hub import interpreter_login
print("DISTANCE TO SIMILARITY CONVERSION")
print("="*50)
print(f"{'Distance':<15} {'Similarity':<15} {'Interpretation':<20}")
print("="*50)
distances=[0.05,0.20,0.40,0.65,0.90]
Interpretation=["Near identical","very similar","Related","Somewhat related","Not related"]

for dist,interp in zip(distances,Interpretation):
  similarity=1-dist
  print(f"{dist:<15.4f} {similarity:<15.4f} {interp:<20}")

DISTANCE TO SIMILARITY CONVERSION
Distance        Similarity      Interpretation      
0.0500          0.9500          Near identical      
0.2000          0.8000          very similar        
0.4000          0.6000          Related             
0.6500          0.3500          Somewhat related    
0.9000          0.1000          Not related         
